### PR TITLE
decouple GraphStructure from other modules through accessors

### LINKED ISSUE #58: Feature Request: Defined access to GraphData
As mentioned in https://github.com/FHell/NetworkDynamics.jl/issues/54#issuecomment-723142323 I'd like to propose a clearly defined set of accessors to get the underlying data of a graph. I think this is a major need for #49. Since it defines a new set of functions for the end users this interface should be designed very carefully though.

From my understanding the main accessors are
```julia
# get the 'view' for the i-th vertex
function get_vertex(gd::GraphData, v_idx) :: AbstractVector{elE}

# get the 'view' for the i-th edge
function get_edge(gd::GraphData, e_idx) :: AbstractVector{elE}

# get the 'view' to the src vertex of the i-th edge
function get_src_vertex(gd::GraphData, e_idx) :: AbstractVector{elV}

# get the 'view' to the dst vertex of the i-th edge
function get_dst_vertex(gd::GraphData, e_idx) :: AbstractVector{elV}

# get all the 'views' to the outgoing edges of the i-th vertex
function get_out_edges(gd::GraphData, v_idx) :: AbstractVector{AbstractVector{elE}}

# get all the 'views' to the incomming edges of the i-th vertex
function get_in_edges(gd::GraphData, v_idx) :: AbstractVector{AbstractVector{elE}}
```
These are the ones used in the core loop. Replacing this would already help decoupling the `NetworkStructures` with the rest of the package, for example one could change to Julias build-in `views` without changing another file. It also simplifies testing of different implementations.

These accessors could be overloaded, for example to get multiple edges at once. One could also think of other useful accesors, for example to get access based on the symbols. Right now, this is done via
```julia
function view_v(gd::GraphData, gs::GraphStruct, sym="")
```
which uses the `GraphStruct`. I think methods like this should be available for the user without even knowing about the existence of `GraphStruct`. Once the `GraphDataBuffer` is in place one should consider why `GraphStruct` and `GraphData` are even separate types since they strongly depend on each other.

#### further thoughts:
   - this is somewhat related to #52 because it would solve the uncertainty about the right way to access the data
   - strongly related to #35, one has to think about how to keep the static values in the `GraphData` up to date with changes to the non-static part (i.e. don't recalculate static edges if the vertex data hasn't changed).
   - right now a lot of the stuff in `NetworkStructures` serves the purpose of caching (i.e. all possible queries like the outgoing edges for every vertex are precomputed during setup). Once one allows access to graph data based on symbols in callbacks it is not possible to compute all of the 'answers' during setup. Maybe one could look into a more automatic approach of [Memoization](https://en.wikipedia.org/wiki/Memoization) based on the arguments of each accessor function.

### PR DESCRIPTION
**Pull request by hexaeder**
this is an resolves #58. Not meant for merging right now.

### CODE REVIEW

**Comment by lindnemi** [comment]
Looks good!

**Comment by lindnemi** [comment]
Yes, PD uses StaticEdgeFunction, so we have to either rewrite that part of PD or get rid of the allocations again: https://github.com/JuliaEnergy/PowerDynamics.jl/search?q=StaticEdgeFunction.

Btw, it looks like it was allocating before, since it returns a tuple. Did allocations increase?

**Comment by hexaeder** [comment]
Tuples are of known length and size and can be stack allocated. Before it was returning a tuple containing of two pointers to heap allocatet Arrays `e_s_v` and `e_s_d` which have been allocated before therefore non allocating function call.

Now it is composing a tuple (non allocating) of to pointers but the pointers refer to arrays which will be created in the function call through these iterators (allocating). But the PD packages doesn't seem to be interested in the full arrays anyway (see [my comment](https://github.com/FHell/NetworkDynamics.jl/issues/58#issuecomment-725374322))

**Comment by hexaeder** [comment]
Should not be merged jet. I'll try to decouple the `GraphStructure` from the rest of the package. As discussed earlier it would be nice to change the module (for example switching to the `GraphDataBuffer`-design) without having to touch a lot of code outside of `NetworkStructures.jl`.

**Comment by lindnemi** [comment]
Nice to see tests for the modules and for allocations. Did you do the benchmarks yet?

Also I think `GetGD` and `GetGS` are abusing multiple dispatch and could be functions instead of types. For what reason were they chosen to be types @FHell ?

**Comment by hexaeder** [comment]
Yes, no perfomance hit compared to master (i think everything boils down to the same machine code anyway due to inlining).

>Also I think GetGD and GetGS are abusing multiple dispatch and could be functions instead of types. For what reason were they chosen to be types @FHell ?

I guess because of the type of `nd`
```julia
nd = network_dynamics(nd_diffusion_vertex, nd_diffusion_edge, g)
typeof(nd) ## isa ODEFunction
typeof(nd.f) ## isa nd_ODE_Static
```
The `ODEFunction` forwards all function calls to its `.f` field. In order to put in in a function one would have to define a new method on the `ODEFunction` object.
```julia
function getGD(nd::ODEFunction{true, T}) where T<:nd_ODE_Static
    nd.f.graph_data
end
```
(in case you are wondering, the first type parameter `true` for `ODEFunctions` is whether it is in place.)

I think this not high priority but certainly something to think about (#35).

**Pull request merged**
