### PR TITLE
added checkbounds prototype

### LINKED ISSUE #23: bounds checking issue in maybe_idx
`maybe_idx` and its 'cousins' disable bounds checking. Yet it's not unlikely that a user passes a parameter array of incorrect dimensions. in this case these functions asses uninitialized memory. we should add a check somewhere

### PR DESCRIPTION
**Pull request by lindnemi**
Closes #23

### CODE REVIEW

**Comment by hexaeder** [comment]
The `checkbounds_p` is fine but i'm not sure wether the boundschecking of `dx` and `x` is necessary. I think if you pass wrong sized initial conditions to an `ODEProblem` there is an error from `DiffEQ.jl`. No need to check this all the time in the core loop?

**Comment by lindnemi** [comment]
Without the checkbounds for x the following bug may occur:
```julia
N = 10
g = erdos_renyi(10,10)

ov = ODEVertex(f! = (dv, v, edges, p, t) -> dv .= v, dim = 1)
se = StaticEdge(f! = (e, v_s, v_d, p, t) -> nothing, dim = 1, coupling = :undirected)

nd! = network_dynamics(ov,se,g)

dx0 = zeros(N)
x0 = ones(1)

nd!(dx0, x0, 1., 0.)
dx0 
```
Here, `dx0` will be filled with uninitialized values. The bug doesn't happen when `dv[1] = v[1]` in the ODEVertex, since then the usual boundscheck happens, except if @inbounds. So it has something to do with how we implement broadcasting... and maybe can be fixed there?

**Comment by lindnemi** [comment]
Creating an ODEProblem out of the MWE may result in a `SegementationFault` when called

**Comment by lindnemi** [comment]
When GraphData is initialized it is guaranteed that v_array and e_array have the correct length. Later we swap them for Arrays of arbitrary length. I guess that would be the best place to do the boundschecking.

**Pull request merged**
